name: API Interaction Workflow

on:
  workflow_dispatch:
    branches:
      - '**'
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'

jobs:
  run-script:
    runs-on: ubuntu-latest
    name: Execute Python Script
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create Credentials File
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json

      - name: Run script
        run: python3 api.py
        env:
          API_CONFIG_JSON: ${{ secrets.API_CONFIG_JSON }}
