name: API Interaction Workflow

on:
  workflow_dispatch:
    branches:
      - '**'
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'

jobs:
  run-script:
    runs-on: ubuntu-latest
    name: Execute Python Script
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create Credentials File
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cryptography

      - name: Decrypt API Details File
        run: |
          openssl enc -aes-256-cbc -d -in api_details.json.enc -out api_details.json -pass pass:${{ secrets.ENCRYPTION_PASSPHRASE }}

      - name: Run script
        run: python3 api.py
