name: Deploy to APP Configs

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'Release Branch'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tagName: ${{ steps.create_tag.outputs.tag_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests azure-appconfiguration

      - name: Push Configurations to Azure App Configuration
        env:
          APP_CONFIG_CONNECTION: ${{ secrets.AZURE_APP_CONFIG_CONNECTION }}
        run: |
          python push_config_to_app_config.py

      - name: Fetch Release Branches
        run: python fetch_release_branches.py

      - name: Create or Update Release Tag
        id: create_tag
        run: |
          TAG_NAME="${{ github.event.inputs.releaseBranch }}-$(date +'%Y%m%d%H%M%S')"
          echo "Creating tag $TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "::set-output name=tag_name::$TAG_NAME"

  build-and-deploy:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.releaseBranch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: kalidynamics2024.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kalidynamics2024.azurecr.io/myapp:${{ needs.prepare.outputs.tagName }}
          file: Dockerfile

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name srisameplewebapp --resource-group srikalidynamic2009 --docker-custom-image-name kalidynamics2024.azurecr.io/myapp:${{ needs.prepare.outputs.tagName }} --docker-registry-server-url https://kalidynamics2024.azurecr.io

      - name: Check Web App Status
        run: |
          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" https://srisameplewebapp.azurewebsites.net)
          if [ $status_code -ne 200 ]; then
            echo "Web app not responding as expected. Status code: $status_code"
            exit 1
          fi
