name: Build and Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Enter the release tag (e.g., v1.0.0)'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/reddyfull/myapp:${{ github.event.inputs.releaseTag }} .
          docker push ghcr.io/reddyfull/myapp:${{ github.event.inputs.releaseTag }}

      - name: Decode KUBECONFIG and Write to File
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yml
        shell: bash

      - name: Deploy to AKS
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yml
          kubectl apply -f .github/kubernetes/aks_deployment.yaml
          kubectl apply -f .github/kubernetes/aks_service.yaml
          kubectl apply -f .github/kubernetes/aks_hpa.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/myapp-deployment
          kubectl get pods -l app=myapp

      - name: Clean Up Old Images (Optional)
        run: |
          # Add steps to clean up old Docker images from the registry if needed
