name: Build and Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Enter the release tag (e.g., v1.0.0)'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode ACR Credentials
        run: echo "${{ secrets.ACR_CREDENTIALS }}" | base64 -d > acr_credentials.json
        shell: bash

      - name: Login to Azure Container Registry
        run: |
          ACR_LOGIN_SERVER=$(jq -r '.["login-server"]' acr_credentials.json)
          ACR_USERNAME=$(jq -r '.username' acr_credentials.json)
          ACR_PASSWORD=$(jq -r '.password' acr_credentials.json)
          echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER --username $ACR_USERNAME --password-stdin
        shell: bash

      - name: Build and Push Docker image
        run: |
          docker build -t $ACR_LOGIN_SERVER/myapp:${{ github.event.inputs.releaseTag }} .
          docker push $ACR_LOGIN_SERVER/myapp:${{ github.event.inputs.releaseTag }}

      - name: Decode KUBECONFIG and Write to File
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yml
        shell: bash

      - name: Deploy to AKS
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yml
          kubectl apply -f .github/kubernetes/aks_deployment.yaml
          kubectl apply -f .github/kubernetes/aks_service.yaml
          kubectl apply -f .github/kubernetes/aks_hpa.yaml
