name: Deploy to Azure Web App

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'Release Branch'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      releaseBranches: ${{ steps.list_branches.outputs.branches }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Fetch Release Branches
        id: list_branches
        run: |
          python fetch_release_branches.py

  build-and-deploy:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.releaseBranch }}

      - name: Create Release Tag
        run: |
          TAG_NAME="release-$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # ... rest of the steps for building and deploying
