name: Deploy to Azure Web App

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'Release Branch'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.releaseBranch }}

      - name: Create or Update Release Tag
        run: |
          TAG_NAME=$(echo "${{ github.event.inputs.releaseBranch }}" | sed 's/[^a-zA-Z0-9._-]/_/g')
          if git rev-parse -q --verify "refs/tags/$TAG_NAME" >/dev/null; then
              echo "Tag exists. Deleting tag $TAG_NAME."
              git tag -d $TAG_NAME
              git push --delete origin $TAG_NAME
          fi
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          TAG_NAME: ${{ github.event.inputs.releaseBranch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/reddyfull/myactions/myapp:$TAG_NAME
          file: Dockerfile

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name srisameplewebapp --resource-group kalidynamics2024 --docker-custom-image-name ghcr.io/reddyfull/myactions/myapp:$TAG_NAME --docker-registry-server-url https://ghcr.io
