name: Fetch and Update Tags

on:
  schedule:
    - cron: '0 23 * * *'  # Runs at 11 PM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Using built-in GITHUB_TOKEN
        run: |
          python .github/scripts/fetch_and_update_tags.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/data/tags.json
          git commit -m "Update tags.json" -a || echo "No changes to commit"
          git push
