name: Fetch and Update Tags

on:
  schedule:
    - cron: '0 23 * * *'  # Runs at 11 PM every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Ensure this secret is set in your repository
        run: |
          python .github/scripts/your_script.py
