name: Update Azure Key Vault

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'main'

jobs:
  update-key-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-keyvault-secrets azure-identity

      - name: Decrypt JSON File
        run: |
          openssl enc -aes-256-cbc -d -salt -pbkdf2 -in keyvault.json.enc -out keyvault.json -pass pass:${{ secrets.ENCRYPTION_PASSPHRASE }}

      - name: Write Azure Credentials to File
        run: echo '${{ secrets.AZURE_CREDENTIALS }}' > azure_credentials.json

      - name: Update Azure Key Vault
        run: python update_keyvault.py
