name: Build and Deploy from Release Tag

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Enter the release tag (e.g., v1.0.0)'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository at a specific tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.releaseTag }}

      # If you need to build an artifact, add the necessary steps here
      # - name: Build Artifact
      #   run: |
      #     commands to build artifact

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/reddyfull/myapp:${{ github.event.inputs.releaseTag }} .
          docker push ghcr.io/reddyfull/myapp:${{ github.event.inputs.releaseTag }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name srisameplewebapp --resource-group kalidynamics2024 --docker-custom-image-name ghcr.io/reddyfull/myapp:${{ github.event.inputs.releaseTag }} --docker-registry-server-url https://ghcr.io
